Repository carina-io/carina, pull requests merged in 2022-09, with the labels that each got.

#131 fix chart bug with modprobe
  charts/Chart.lock
  charts/Chart.yaml
  charts/templates/csi-node.yaml
  charts/values.yaml
Labels: approved, lgtm, size/M

#134 fix chart debug with multi image error
  charts/templates/csi-driver.yaml
  charts/values.yaml
Labels: approved, lgtm

#135 add ci.yaml
  .github/workflows/ci.yaml
  test/e2e/deploycarina/csi-carina-controller.yaml
  test/e2e/deploycarina/csi-carina-node.yaml
Labels: approved, lgtm

#136 modify ci security and build job
  .github/workflows/ci.yaml
Labels: approved, lgtm, ok-to-test, size/L

#138 modify ci job kubernetes
  .github/workflows/ci.yaml
  test/e2e/deploycarina/csi-carina-controller.yaml
  test/e2e/deploycarina/csi-carina-node.yaml
Labels: approved, lgtm, size/L

#137 Update csi-carina-controller.yaml
  deploy/kubernetes/csi-carina-controller.yaml
Labels: approved, kind/bug, lgtm, size/XS

#139 modify image pull policy
  .github/workflows/ci.yaml
  test/e2e/deploycarina/csi-carina-controller.yaml
  test/e2e/deploycarina/csi-carina-node.yaml
  test/e2e/raw/block_raw_pvc.go
Labels: approved, lgtm, ok-to-test, size/L

#140 Add Kubernetes support range
  README.md
  README_zh.md
Labels: approved, lgtm

#142 upgrade function
  deploy/kubernetes/deploy.sh
Labels: approved, lgtm, size/S

#145 fix chart debug for psp and toprettyjson comfigmap
  charts/templates/NOTES.txt
  charts/templates/_helpers.tpl
  charts/templates/csi-config-map.yaml
  charts/templates/csi-controller-psp.yaml
  charts/templates/csi-node-psp.yaml
  charts/templates/storageclass-raw.yaml
  charts/templates/storageclass.yaml
  charts/templates/test/deploy-demo.yaml
  charts/values.yaml
Labels: approved, lgtm, size/L

#144 fix bug for delete lv when node is not ready
  controllers/node_controller.go
Labels: approved, lgtm, ok-to-test, size/M
