Repository carina-io/carina, pull requests merged in 2022-12, with the labels that each got.

#152 fix: remove redundant partprobe for lvm
  pkg/devicemanager/lvmd/interface.go
  pkg/devicemanager/lvmd/lvm.go
  runners/devicecheck.go
  runners/troubleshoot.go
Labels: approved, lgtm, size/S

#153 Create lvupgrade.sh
  deploy/kubernetes/lvupgrade.sh
Labels: approved, lgtm, size/XS

#154 add code of conduct
  README.md
Labels: approved, lgtm, size/XS

#155 Release 1.0
  deploy/kubernetes/lvupgrade.sh
  pkg/devicemanager/partition/partition.go
Labels: approved, size/M

#156 Modify the bug of the raw disk partition for capacity expansionSigne…
  docs/design/design-raw-manger.md
  pkg/devicemanager/partition/partition.go
  pkg/devicemanager/partition/partition_test.go
Labels: approved, lgtm, size/M
