Repository carina-io/carina, pull requests merged in 2022-08, with the labels that each got.

#114 Add Owner and Maintainers
  MAINTAINERS.md
  OWNERS
Labels: approved, ok-to-test

#119 [doc] change snapshot support to disabled
  README.md
Labels: approved, size/XS

#117 Feature/v0.11 update script
  CHANGELOG.md
  README.md
  README_zh.md
  charts/Chart.yaml
  charts/README.md
  charts/templates/csi-service.yaml
  cmd/carina-controller/run/root.go
  cmd/carina-controller/run/run.go
  deploy/kubernetes/lvupgrade.sh
  deploy/kubernetes/storageclass-lvm.yaml
  docs/manual/api.md
  docs/manual/capacity-scheduler.md
  docs/manual/device-register.md
  docs/manual/disk-manager.md
  docs/manual/install.md
  docs/manual/metrics.md
  docs/manual/pvc-bcache.md
  docs/manual_zh/api.md
  docs/manual_zh/capacity-scheduler.md
  docs/manual_zh/device-register.md
  docs/manual_zh/disk-manager.md
  docs/manual_zh/disk-speed-limit.md
  docs/manual_zh/install-v0.11.0.md
  docs/manual_zh/install.md
  docs/manual_zh/metrics.md
  docs/manual_zh/pvc-bcache.md
  docs/user-guide.md
  examples/middleware/mysql.md
  test/e2e/deploycarina/csi-carina-controller.yaml
  test/e2e/deploycarina/csi-carina-node.yaml
Labels: approved, size/L

#120 update e2e deploy yaml,modify Makefile and e2e.sh
  deploy/kubernetes/csi-config-map.yaml
  test/e2e/Makefile
  test/e2e/deploycarina/crd-logicvolume.yaml
  test/e2e/deploycarina/crd-nodestoreresource.yaml
  test/e2e/deploycarina/csi-carina-node.yaml
  test/e2e/deploycarina/csi-config-map.yaml
  test/e2e/e2e.sh
Labels: approved, lgtm

#121 Develop/v0.11.0
  README_zh.md
  charts/Chart.yaml
  charts/templates/crds/carina.storage.io_logicvolumes.yaml
  charts/templates/crds/carina.storage.io_nodestorageresources.yaml
  charts/templates/crds/crd-logicvolume.yaml
  charts/templates/crds/crd-nodestoreresource.yaml
  charts/templates/csi-controller.yaml
  charts/templates/csi-driver.yaml
  charts/templates/csi-node.yaml
  charts/templates/mutatingwebhooks.yaml
  charts/values.yaml
  debug/Makefile
  skaffold.yaml
Labels: approved, lgtm, size/XL

#122 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#123 refactor scheduler logic
  OWNERS
  cmd/carina-controller/run/run.go
  cmd/carina-node/run/run.go
  constants.go
  controllers/logicvolume_controller.go
  deploy/kubernetes/csi-carina-controller.yaml
  deploy/kubernetes/csi-carina-node.yaml
  deploy/kubernetes/deploy.sh
  deploy/kubernetes/prometheus-service-monitor.yaml
  deploy/kubernetes/prometheus.yaml.tmpl
  deploy/kubernetes/storageclass-lvm.yaml
  deploy/kubernetes/storageclass-raw.yaml
  docs/manual_zh/install-v0.11.0.md
  getter/retry_getter.go
  hook/mutate_pod.go
  pkg/csidriver/driver/controller.go
  pkg/csidriver/driver/k8s/logicvolume_service.go
  pkg/csidriver/driver/k8s/node_service.go
  pkg/csidriver/driver/node.go
  pkg/devicemanager/partition/partition.go
  pkg/devicemanager/volume/volume.go
  runners/nodestorageresource.go
  scheduler/constants.go
  scheduler/go.mod
  scheduler/go.sum
  scheduler/schedulerplugin/localstorage/k8s.go
  scheduler/schedulerplugin/localstorage/storage-plugins.go
  scheduler/schedulerplugin/localstorage/storage-plugins_test.go
  test/e2e/deploycarina/csi-carina-controller.yaml
  utils/exec/exec.go
Labels: enhancement, approved, kind/bug, lgtm, size/XXL

#124 Modify documents and delete redundant files
  CHANGELOG.md
  charts/Chart.yaml
  charts/values.yaml
  deploy/kubernetes/csi-carina-node.yaml
  deploy/kubernetes/csi-config-map.yaml
  deploy/kubernetes/deploy.sh
  deploy/kubernetes/storageclass-raw.yaml
  docs/design/design-disk-manager.md
  docs/design/design-raid-manager.md
  docs/manual/development.md
  docs/manual_zh/development.md
  examples/feature/deployment.yaml
  examples/feature/pod-clone.yaml
  examples/feature/pod-restore.yaml
  examples/feature/pod.yaml
  examples/feature/pvc-clone.yaml
  examples/feature/pvc-restore.yaml
  examples/feature/pvc.yaml
  examples/feature/snapshot.yaml
  examples/feature/snapshotclass.yaml
  examples/feature/storageclass.yaml
  examples/kubernetes/storageclass-raw-exclusivity.yaml
  examples/kubernetes/storageclass-raw.yaml
  examples/kubernetes/storageclass.yaml
  examples/kubernetes/storageclass.yaml.auto.migrate
  examples/kubernetes/storageclass.yaml.bcache
  examples/kubernetes/storageclass.yaml.support
  scheduler/charts/.helmignore
  scheduler/charts/Chart.yaml
  scheduler/charts/templates/NOTES.txt
  scheduler/charts/templates/_helpers.tpl
  scheduler/charts/templates/configmap.yaml
  scheduler/charts/templates/csi-config-map.yaml
  scheduler/charts/templates/deployment.yaml
  scheduler/charts/templates/hpa.yaml
  scheduler/charts/templates/rbac.yaml
  scheduler/charts/templates/serviceaccount.yaml
  scheduler/charts/values.yaml
  test/e2e/deploycarina/csi-carina-controller.yaml
  test/e2e/deploycarina/csi-carina-node.yaml
Labels: approved, lgtm, size/XL

#125 Modifying a Mirror Vault
  deploy/kubernetes/csi-carina-controller.yaml
Labels: approved, lgtm, size/XS

#126 fix chart debug with livenessProbe
  charts/values.yaml
Labels: approved, lgtm, size/XS

#127 Develop/v0.11.0
  charts/templates/rbac-csi-controller.yaml
Labels: approved, lgtm, size/M
