Repository carina-io/carina, pull requests merged in 2023-02, with the labels that each got.

#167 update metrics docs
  docs/manual/metrics.md
  docs/manual_zh/metrics.md
  docs/user-guide.md
  examples/kubernetes/lvm-block-pvc.yaml
  examples/kubernetes/storageclass-raw.yaml
Labels: approved, lgtm, size/L

#171 optimize upgrade and deployment scripts
  deploy/kubernetes/deploy.sh
  deploy/kubernetes/lvupgrade.sh
Labels: approved, lgtm, size/M

#172 modifying carina v0.9.0-->0.11.x upgrade logic
  cmd/carina-node/run/run.go
  deploy/kubernetes/lvupgrade.sh
  pkg/devicemanager/manager.go
  runners/troubleshoot.go
Labels: approved, lgtm, size/M

#173 fix bug for raw exdedartition
  pkg/devicemanager/partition/partition.go
Labels: approved, lgtm, size/XS

#174 fix debug for exentend disk in checkout mount point for target path
  pkg/devicemanager/partition/partition.go
  pkg/devicemanager/partition/partition_test.go
Labels: approved, lgtm, size/S
